name: CI

env:
  PROJECT: NymphCastRPC

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  gcc:
    strategy:
      matrix:
        version: [11]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install GCC ${{ matrix.version }}
        run: sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}
      - name: install required packages
        run: sudo apt-get -y install libpoco-dev
      - name: Build RPC
        env:
          CXX: g++-${{ matrix.version }}
        run: make all
